#!/usr/bin/env python
from __future__ import print_function
import sys
import os
import argparse
import subprocess
import requests

url = "https://github.com/nf-core/test-datasets/raw/neutronstar/tests/testrun_supernova.tar.gz"
archive = url.split('/')[-1:][0]

if __name__ == '__main__':

  parser = argparse.ArgumentParser()
  parser.add_argument('--id')

  args, unknown = parser.parse_known_args()

  if 'id' in args:
    r = requests.get(url)
    open(archive , 'wb').write(r.content)
    tar = subprocess.call(['tar', 'zfx', archive])
    tar = subprocess.call(['mv', 'testrun_supernova', args.id])
  else:
    sys.exit(1)
